# Default configuration for Paper Manager
# Balanced settings for general use

[api]
model = "google/gemini-2.0-flash-001"
temperature = 0.3
max_tokens = 1000000
api_key = ""  # Add your OpenRouter API key here

[paper]
types = ["agent_rl", "Interpretability", "Efficiency"]
csv_file = "papers.csv"

[ui]
theme = "soft"
chatbot_height = 500
debug = true